/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * service-auth-api
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosInstance
} from 'axios';

import { customInstance } from './http';
export interface AccountResponse {
  account_type: string;
  created_at: string;
  /** @nullable */
  deleted_at?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  uid: string;
  updated_at: string;
  /** @nullable */
  username?: string | null;
}

export interface AuthContextResponse {
  /** @nullable */
  auth_type?: string | null;
  authenticated: boolean;
  /** @nullable */
  email?: string | null;
  scopes: string[];
  /** @nullable */
  subject?: string | null;
}

export interface BuildMetadata {
  /** @nullable */
  built_at?: string | null;
  /** @nullable */
  git_sha?: string | null;
  version: string;
}

export interface CompleteLoginRequest {
  token: string;
}

export interface CreateAccount {
  account_type: string;
  /** @nullable */
  created_by?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  username?: string | null;
}

export interface EmailActionAccepted {
  accepted: boolean;
}

export interface EmailLoginResult {
  auth_type: string;
  authenticated: boolean;
  session_token: string;
  subject: string;
}

export interface EmailOnlyRequest {
  email: string;
  /** @nullable */
  rewrite?: string | null;
}

export interface EmailVerifyResult {
  email: string;
  verified: boolean;
}

export interface Health {
  build: BuildMetadata;
  status: string;
}

export interface PreferencesResponse {
  language: string;
  supported_languages: string[];
  supported_themes: string[];
  theme: string;
}

export interface RegisterEmailRequest {
  /** @nullable */
  display_name?: string | null;
  email: string;
  /** @nullable */
  rewrite?: string | null;
}

export interface UpdateAccount {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  updated_by?: string | null;
  /** @nullable */
  username?: string | null;
}

export interface UpdatePreferencesRequest {
  /** @nullable */
  language?: string | null;
  /** @nullable */
  theme?: string | null;
}

export interface VerifyQuery {
  /** @nullable */
  rewrite?: string | null;
  token: string;
}

export type VerifyEmailParams = {
/**
 * Verification token
 */
token: string;
};

export const getServiceAuthApi = (axiosInstance: AxiosInstance = axios) => {
const createAccount = (
    createAccount: CreateAccount,
 ) => {
      return customInstance<AccountResponse>(
      {url: `/api/v1/accounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createAccount
    },
      );
    }
  
const getAccount = (
    uid: string,
 ) => {
      return customInstance<AccountResponse>(
      {url: `/api/v1/accounts/${uid}`, method: 'GET'
    },
      );
    }
  
const deleteAccount = (
    uid: string,
 ) => {
      return customInstance<void>(
      {url: `/api/v1/accounts/${uid}`, method: 'DELETE'
    },
      );
    }
  
const updateAccount = (
    uid: string,
    updateAccount: UpdateAccount,
 ) => {
      return customInstance<AccountResponse>(
      {url: `/api/v1/accounts/${uid}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateAccount
    },
      );
    }
  
const context = (
    
 ) => {
      return customInstance<AuthContextResponse>(
      {url: `/api/v1/auth/context`, method: 'GET'
    },
      );
    }
  
const requestEmailLogin = (
    emailOnlyRequest: EmailOnlyRequest,
 ) => {
      return customInstance<EmailActionAccepted>(
      {url: `/api/v1/auth/login/email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailOnlyRequest
    },
      );
    }
  
const completeEmailLogin = (
    completeLoginRequest: CompleteLoginRequest,
 ) => {
      return customInstance<EmailLoginResult>(
      {url: `/api/v1/auth/login/email/complete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: completeLoginRequest
    },
      );
    }
  
const registerEmail = (
    registerEmailRequest: RegisterEmailRequest,
 ) => {
      return customInstance<EmailActionAccepted>(
      {url: `/api/v1/auth/register/email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerEmailRequest
    },
      );
    }
  
const verifyEmail = (
    params: VerifyEmailParams,
 ) => {
      return customInstance<EmailVerifyResult>(
      {url: `/api/v1/auth/verify/email`, method: 'GET',
        params
    },
      );
    }
  
const resendVerifyEmail = (
    emailOnlyRequest: EmailOnlyRequest,
 ) => {
      return customInstance<EmailActionAccepted>(
      {url: `/api/v1/auth/verify/email/resend`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailOnlyRequest
    },
      );
    }
  
const health = (
    
 ) => {
      return customInstance<Health>(
      {url: `/api/v1/health`, method: 'GET'
    },
      );
    }
  
const getPreferences = (
    
 ) => {
      return customInstance<PreferencesResponse>(
      {url: `/api/v1/preferences`, method: 'GET'
    },
      );
    }
  
const updatePreferences = (
    updatePreferencesRequest: UpdatePreferencesRequest,
 ) => {
      return customInstance<PreferencesResponse>(
      {url: `/api/v1/preferences`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updatePreferencesRequest
    },
      );
    }
  
return {createAccount,getAccount,deleteAccount,updateAccount,context,requestEmailLogin,completeEmailLogin,registerEmail,verifyEmail,resendVerifyEmail,health,getPreferences,updatePreferences}};
export type CreateAccountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['createAccount']>>>
export type GetAccountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['getAccount']>>>
export type DeleteAccountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['deleteAccount']>>>
export type UpdateAccountResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['updateAccount']>>>
export type ContextResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['context']>>>
export type RequestEmailLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['requestEmailLogin']>>>
export type CompleteEmailLoginResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['completeEmailLogin']>>>
export type RegisterEmailResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['registerEmail']>>>
export type VerifyEmailResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['verifyEmail']>>>
export type ResendVerifyEmailResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['resendVerifyEmail']>>>
export type HealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['health']>>>
export type GetPreferencesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['getPreferences']>>>
export type UpdatePreferencesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getServiceAuthApi>['updatePreferences']>>>
