/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * auth-api
 * OpenAPI spec version: 0.1.0
 */
import type {
  Health
} from './models';

import { customInstance } from './http';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getAuthApi = () => {
const health = (
    
 options?: SecondParameter<typeof customInstance<Health>>,) => {
      return customInstance<Health>(
      {url: `/api/v1/health`, method: 'GET'
    },
      options);
    }
  
return {health}};
export type HealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuthApi>['health']>>>
